# -*- coding: utf-8 -*-
import json

D = {}

D["a37"] = {
 "title_en": "Geographic heterogeneity in outcomes of intravascular ultrasound-guided vs angiography-guided percutaneous coronary intervention: a meta-analysis of randomized trials",
 "title_es": "Heterogeneidad geográfica en los resultados del intervencionismo coronario percutáneo guiado por ecografía intravascular frente al guiado por angiografía: metaanálisis de ensayos aleatorizados",
 "es": {
  "resumen": "Metaanálisis de 17 ensayos aleatorizados (14.033 pacientes) que compara ICP guiado por IVUS frente a guiado por angiografía. El IVUS redujo la muerte cardiaca (RR 0,71; IC 95% 0,53-0,94; P = 0,022), pero el beneficio se concentró en los ensayos del este asiático (RR 0,56) y desapareció en los no asiáticos (RR 1,23; P de interacción < 0,001).",
  "why": "explica una discrepancia que venía incomodando a la comunidad intervencionista: los ensayos europeos recientes con IVUS resultaron neutros mientras los asiáticos eran claramente positivos, y aquí la heterogeneidad geográfica se contrasta como hipótesis primaria preespecificada, no como un análisis post hoc de conveniencia. La divergencia afecta a muerte cardiaca, infarto y revascularización del vaso diana y a los MACE, pero no a la trombosis del stent, que se redujo de forma consistente en todas las geografías. Para el cardiólogo clínico, el mensaje es que el beneficio del IVUS no reside en mirar, sino en qué se hace con lo que se ve: la forma de aplicar los criterios de optimización del implante puede explicar buena parte de la diferencia, y extrapolar sin más las magnitudes de efecto asiáticas a nuestro medio no está justificado.",
  "deque": "El ICP guiado por ecografía intravascular (IVUS) ha mejorado los resultados en ensayos aleatorizados, pero varios ensayos europeos recientes han comunicado resultados neutros pese a los hallazgos positivos de los estudios del este asiático. Los autores plantearon si el beneficio es consistente entre entornos. Se revisaron sistemáticamente y se metaanalizaron los ensayos aleatorizados que comparaban ICP guiado por IVUS frente a ICP guiado por angiografía con stent farmacoactivo. Los riesgos relativos (RR) agrupados se calcularon con modelos de efectos aleatorios de máxima verosimilitud restringida con ajuste de Hartung-Knapp-Sidik-Jonkman. La modificación geográfica del efecto se preespecificó como hipótesis principal, y el test de interacción para la muerte cardiaca fue el análisis primario.",
  "resultados": "Se incluyeron 17 ensayos (14.033 pacientes; 10 del este asiático con 10.155 pacientes y 7 no asiáticos con 3.878). El RR agrupado de muerte cardiaca fue 0,71 (IC 95% 0,53-0,94; P = 0,022), con interacción geográfica significativa: RR 0,56 (0,46-0,69) en los ensayos del este asiático frente a RR 1,23 (0,85-1,76) en los no asiáticos (P de interacción < 0,001). Los efectos del tratamiento también divergieron para el infarto del vaso diana (P de interacción = 0,011), la revascularización del vaso diana (P de interacción = 0,004) y los eventos cardiovasculares adversos mayores o MACE (P de interacción = 0,040). La guía por IVUS redujo la trombosis definitiva del stent (RR 0,39; IC 95% 0,19-0,79), en este caso sin interacción geográfica (P de interacción = 0,433). La mortalidad por cualquier causa fue similar (RR 0,89; IC 95% 0,76-1,04).",
  "conclusiones": "Considerando todos los estudios, el ICP guiado por IVUS redujo la muerte cardiaca, el infarto del vaso diana, la revascularización del vaso diana, los MACE y la trombosis del stent. Sin embargo, hubo interacciones significativas, de modo que las reducciones relativas de muerte cardiaca, infarto del vaso diana, revascularización del vaso diana y MACE fueron mayores en los ensayos asiáticos que en los no asiáticos (aunque la trombosis del stent se redujo de forma consistente entre geografías). Las diferencias en cómo se utilizó la información derivada del IVUS para optimizar el implante del stent pueden contribuir a esta heterogeneidad geográfica."
 },
 "en": {
  "resumen": "Meta-analysis of 17 randomized trials (14,033 patients) comparing IVUS-guided with angiography-guided PCI. IVUS reduced cardiac death (RR 0.71; 95% CI 0.53-0.94; P = 0.022), but the benefit was confined to East Asian trials (RR 0.56) and vanished in non-Asian ones (RR 1.23; interaction P < 0.001).",
  "why": "it accounts for a discrepancy that has been unsettling the interventional community: recent European IVUS trials were neutral while East Asian trials were clearly positive, and here geographic heterogeneity was tested as the pre-specified primary hypothesis rather than as a convenient post hoc analysis. The divergence affects cardiac death, target-vessel infarction and revascularization, and MACE, but not stent thrombosis, which was reduced consistently across geographies. For the clinical cardiologist the message is that the benefit of IVUS lies not in looking but in what is done with what is seen: how stent optimization criteria are applied may explain much of the difference, and simply extrapolating Asian effect sizes to our setting is not justified.",
  "deque": "IVUS-guided PCI has improved outcomes in randomized trials, yet several recent European trials have reported neutral results despite positive findings from East Asian studies. The authors asked whether the benefit is consistent across settings. Randomized trials comparing IVUS-guided with angiography-guided drug-eluting stent PCI were systematically reviewed and meta-analysed. Pooled risk ratios (RRs) were derived from restricted maximum likelihood random-effects models with Hartung-Knapp-Sidik-Jonkman adjustment. Geographic effect modification was pre-specified as the primary hypothesis, and the interaction test for cardiac death was the primary analysis.",
  "resultados": "Seventeen trials were included (14,033 patients; 10 East Asian with 10,155 patients and 7 non-Asian with 3,878). The pooled RR for cardiac death was 0.71 (95% CI 0.53-0.94; P = 0.022), with a significant geographic interaction: RR 0.56 (0.46-0.69) in East Asian trials vs RR 1.23 (0.85-1.76) in non-Asian trials (interaction P < 0.001). Treatment effects also diverged for target-vessel myocardial infarction (interaction P = 0.011), target-vessel revascularization (interaction P = 0.004) and major adverse cardiovascular events, MACE (interaction P = 0.040). IVUS guidance reduced definite stent thrombosis (RR 0.39; 95% CI 0.19-0.79), here without geographic interaction (interaction P = 0.433). All-cause death was similar (RR 0.89; 95% CI 0.76-1.04).",
  "conclusiones": "Considering all studies, IVUS-guided PCI reduced cardiac death, target-vessel myocardial infarction, target-vessel revascularization, MACE and stent thrombosis. However, significant interactions were present, such that the relative reductions in cardiac death, target-vessel myocardial infarction, target-vessel revascularization and MACE were greater in the Asian than in the non-Asian trials (although stent thrombosis was reduced consistently across geographies). Differences in how the information derived from IVUS was used to optimize stent implantation may contribute to this geographic heterogeneity."
 }
}

D["a38"] = {
 "title_en": "Half-dose rivaroxaban vs antiplatelet therapy for preventing silent cerebral embolism after left atrial appendage occlusion: the HALO-SCE trial",
 "title_es": "Rivaroxabán a media dosis frente a antiagregación para prevenir la embolia cerebral silente tras el cierre de la orejuela izquierda: el ensayo HALO-SCE",
 "es": {
  "resumen": "Ensayo aleatorizado en 164 pacientes con cierre exitoso de la orejuela izquierda que compara rivaroxabán 10 mg/día frente a antiagregación. La incidencia de nuevas lesiones embólicas cerebrales silentes fue del 12,2% con rivaroxabán frente al 31,7% con antiagregación (P = 0,005), con mejores trayectorias cognitivas al año.",
  "why": "el tratamiento antitrombótico a largo plazo tras el cierre de la orejuela sigue siendo un terreno de consenso débil, y este es el primer ensayo aleatorizado que utiliza la resonancia de difusión seriada y test cognitivos repetidos como variable principal en esta población. Muestra que la antiagregación deja pasar un número nada trivial de embolias silentes —casi un tercio de los pacientes— y que media dosis de rivaroxabán las reduce a la vez que preserva mejor la puntuación en MMSE y MoCA. Es un tamaño muestral pequeño y la variable clínica compuesta no alcanzó significación, de modo que el hallazgo abre una vía plausible pero todavía no obliga a cambiar la pauta en pacientes candidatos a anticoagulación tras cierre de orejuela.",
  "deque": "La estrategia antitrombótica óptima a largo plazo tras el cierre percutáneo de la orejuela izquierda (LAAO) sigue sin determinarse. El estudio se propuso investigar si el rivaroxabán a media dosis (10 mg al día) reduce mejor las lesiones embólicas cerebrales silentes (SCE) y preserva la función cognitiva en comparación con la antiagregación tras un LAAO exitoso. Se trata de un ensayo controlado aleatorizado, prospectivo, multicéntrico e iniciado por investigadores, en el que los pacientes con LAAO exitoso confirmado a los 45 días del procedimiento se asignaron 1:1 a rivaroxabán a media dosis o a antiagregación. Se repitieron la resonancia magnética potenciada en difusión y las evaluaciones cognitivas a los 90, 180 y 365 días del LAAO. La variable principal fue la incidencia por paciente de cualquier SCE de nueva aparición durante el seguimiento. Las variables secundarias incluyeron las trayectorias cognitivas, la carga de SCE y un compuesto de mortalidad por cualquier causa, eventos tromboembólicos clínicos y hemorragia mayor.",
  "resultados": "Entre diciembre de 2022 y febrero de 2025 se aleatorizaron 164 pacientes. La incidencia por paciente de nuevas SCE fue significativamente menor con rivaroxabán a media dosis que con antiagregación: 10/82 (12,2%) frente a 26/82 (31,7%); P = 0,005. A los 365 días, las diferencias entre grupos derivadas del modelo favorecieron al rivaroxabán a media dosis tanto en el Mini-Mental State Examination (2,56; IC 95% 1,11-4,01; P < 0,001) como en el Montreal Cognitive Assessment (2,67; IC 95% 1,07-4,26; P = 0,001). El compuesto clínico ocurrió en el 2,4% del grupo de rivaroxabán a media dosis frente al 11,0% del grupo de antiagregación (P = 0,057).",
  "conclusiones": "En pacientes candidatos a anticoagulación oral tras un cierre exitoso de la orejuela izquierda, el rivaroxabán 10 mg al día redujo significativamente las embolias cerebrales silentes y mantuvo mejor la función cognitiva en comparación con la antiagregación, con un número numéricamente menor de eventos clínicos del compuesto."
 },
 "en": {
  "resumen": "Randomized trial in 164 patients with successful left atrial appendage occlusion comparing rivaroxaban 10 mg daily with antiplatelet therapy. The incidence of new silent cerebral embolic lesions was 12.2% with rivaroxaban vs 31.7% with antiplatelet therapy (P = 0.005), with better cognitive trajectories at 1 year.",
  "why": "long-term antithrombotic therapy after left atrial appendage occlusion still rests on weak consensus, and this is the first randomized trial to use serial diffusion-weighted MRI and repeated cognitive testing as the primary endpoint in this population. It shows that antiplatelet therapy lets through a far from trivial number of silent emboli — almost a third of patients — and that half-dose rivaroxaban reduces them while better preserving MMSE and MoCA scores. The sample is small and the composite clinical endpoint did not reach significance, so the finding opens a plausible avenue but does not yet mandate a change of regimen in patients eligible for anticoagulation after appendage occlusion.",
  "deque": "The optimal long-term antithrombotic strategy after left atrial appendage occlusion (LAAO) remains undetermined. The study set out to investigate whether half-dose rivaroxaban (10 mg daily) better reduces silent cerebral embolic lesions (SCEs) and preserves cognitive function compared with antiplatelet therapy after successful LAAO. In this investigator-initiated, prospective, multicenter, randomized controlled trial, patients with successful LAAO confirmed 45 days after the procedure were assigned 1:1 to half-dose rivaroxaban or antiplatelet therapy. Diffusion-weighted magnetic resonance imaging and cognitive assessments were repeated 90, 180 and 365 days after LAAO. The primary outcome was the patient-level incidence of any newly detected SCE during follow-up. Secondary outcomes included cognitive trajectories, SCE burden, and a composite of all-cause mortality, clinical thromboembolic events and major bleeding.",
  "resultados": "Between December 2022 and February 2025, 164 patients were randomized. The patient-level incidence of new SCEs was significantly lower with half-dose rivaroxaban than with antiplatelet therapy: 10/82 (12.2%) vs 26/82 (31.7%); P = 0.005. At 365 days, model-derived between-group differences favoured half-dose rivaroxaban for both the Mini-Mental State Examination (2.56; 95% CI 1.11-4.01; P < 0.001) and the Montreal Cognitive Assessment (2.67; 95% CI 1.07-4.26; P = 0.001). The composite clinical outcome occurred in 2.4% of the half-dose rivaroxaban group vs 11.0% of the antiplatelet therapy group (P = 0.057).",
  "conclusiones": "In patients eligible for oral anticoagulation after successful LAAO, rivaroxaban 10 mg daily significantly reduced silent cerebral emboli and better maintained cognitive function compared with antiplatelet therapy, with numerically fewer composite clinical events."
 }
}

D["a39"] = {
 "title_en": "Important Residual Lesions and Early Unplanned Reinterventions After Pediatric Cardiac Surgery: A Scientific Statement From the American Heart Association",
 "title_es": "Lesiones residuales relevantes y reintervenciones precoces no planificadas tras la cirugía cardiaca pediátrica: documento científico de la American Heart Association",
 "es": {
  "resumen": "Documento científico de la American Heart Association sobre las lesiones residuales relevantes tras la cirugía cardiaca congénita y las reintervenciones precoces no planificadas que motivan, que ocurren en torno al 5% de todas las operaciones cardiacas pediátricas. Revisa incidencia, factores de riesgo, monitorización posoperatoria, imagen no invasiva, cateterismo diagnóstico e intervencionista y reoperación precoz.",
  "why": "sitúa la lesión residual posquirúrgica como un factor causal principal de malos resultados en cirugía cardiaca congénita, y no como una complicación inevitable. Al documentar una variabilidad amplia entre centros en la incidencia y el momento de las reintervenciones no planificadas, convierte el problema en un objetivo explícito de mejora de la calidad asistencial. Para el cardiólogo, ordena en un solo texto los indicadores clínicos que deben hacer sospechar una lesión residual y el papel respectivo de la imagen no invasiva, el cateterismo y la reoperación precoz.",
  "deque": "Documento científico (scientific statement) de la American Heart Association dedicado a las lesiones residuales relevantes y a las reintervenciones cardiacas precoces no planificadas durante el ingreso índice tras la cirugía cardiaca pediátrica. Está dirigido al equipo multidisciplinar que atiende a estos pacientes —cardiología pediátrica, cirugía cardiaca congénita, anestesia, perfusión y cuidados perioperatorios— y aborda la incidencia, los factores de riesgo y los resultados clínicos de estas situaciones, las estrategias de monitorización posoperatoria y los indicadores clínicos sugestivos de lesión residual, las modalidades de imagen no invasiva para su identificación y cuantificación, el papel del cateterismo cardiaco diagnóstico e intervencionista, las consideraciones quirúrgicas para la reoperación precoz y la comunicación con pacientes y familias. El abstract disponible no especifica a qué versión previa sustituye.",
  "resultados": [
   "Los resultados óptimos en cirugía cardiaca congénita dependen de la experiencia y el juicio de un equipo clínico multidisciplinar integrado, y requieren una comprensión completa de la anatomía y la fisiología del paciente, un plan terapéutico apropiado, una operación meticulosamente ejecutada y técnicamente óptima, facilitada por estrategias de anestesia y perfusión específicas para la lesión, y unos cuidados perioperatorios expertos.",
   "La presencia de lesiones residuales relevantes tras la cirugía es un factor principal que contribuye a los resultados adversos y puede obligar a reintervenciones cardiacas precoces no planificadas durante el ingreso índice.",
   "Estas reintervenciones ocurren en aproximadamente el 5% de todas las operaciones cardiacas pediátricas, con una incidencia mayor en los pacientes de menor edad y en los procedimientos más complejos.",
   "La presencia de lesiones residuales significativas y la necesidad de reintervenciones no planificadas se asocian de forma intensa a mayor morbilidad, mayor mortalidad y mayor consumo de recursos.",
   "Existe una amplia variación entre centros en la incidencia y el momento de las reintervenciones no planificadas, lo que señala una oportunidad concreta de mejora de la calidad.",
   "El documento revisa las estrategias de monitorización posoperatoria y los indicadores clínicos que deben hacer sospechar una lesión residual, junto con una panorámica de las modalidades de imagen no invasiva empleadas para identificarlas y cuantificarlas.",
   "Se discuten el papel del cateterismo cardiaco diagnóstico e intervencionista en el manejo de las lesiones residuales y las consideraciones quirúrgicas para la reoperación precoz.",
   "Se subraya la importancia de la comunicación con los pacientes y sus familias, y se identifican las áreas clave para la investigación futura."
  ],
  "conclusiones": "Para la práctica clínica, el documento consolida un principio operativo: ante un posoperatorio de cirugía cardiaca congénita que no evoluciona como se esperaba, la lesión residual debe buscarse activamente y de forma precoz, apoyándose primero en la monitorización posoperatoria y en los indicadores clínicos de sospecha, después en la imagen no invasiva y, cuando proceda, en el cateterismo diagnóstico o intervencionista o en la reoperación. Al tratarse de un evento que afecta a alrededor del 5% de las operaciones, con mayor riesgo en los niños más pequeños y las cirugías más complejas, y con una variabilidad amplia entre centros, cada equipo debería conocer sus propias tasas y tiempos de reintervención como indicador de calidad. La comunicación explícita con la familia sobre esta posibilidad forma parte del estándar de atención. El texto no aporta recomendaciones numeradas con clase ni nivel de evidencia."
 },
 "en": {
  "resumen": "American Heart Association scientific statement on important residual lesions after congenital cardiac surgery and the early unplanned reinterventions they prompt, which occur in about 5% of all pediatric cardiac operations. It reviews incidence, risk factors, postoperative monitoring, noninvasive imaging, diagnostic and interventional catheterization, and early reoperation.",
  "why": "it frames postoperative residual lesions as a principal causal factor behind poor outcomes in congenital cardiac surgery rather than as an unavoidable complication. By documenting wide center-level variation in the incidence and timing of unplanned reinterventions, it turns the problem into an explicit quality-improvement target. For the cardiologist, it brings together in one text the clinical indicators that should raise suspicion of a residual lesion and the respective roles of noninvasive imaging, catheterization and early reoperation.",
  "deque": "American Heart Association scientific statement devoted to important residual lesions and early unplanned cardiac reinterventions during the index hospitalization after pediatric cardiac surgery. It addresses the multidisciplinary team caring for these patients — pediatric cardiology, congenital cardiac surgery, anesthesia, perfusion and perioperative care — and covers the incidence, risk factors and clinical outcomes of these situations, postoperative monitoring strategies and clinical indicators suggestive of a residual lesion, the noninvasive imaging modalities used for their identification and quantification, the role of diagnostic and interventional cardiac catheterization, surgical considerations for early reoperation, and communication with patients and families. The available abstract does not state which previous version it supersedes.",
  "resultados": [
   "Optimal outcomes in congenital heart surgery depend on the expertise and judgment of an integrated multidisciplinary clinical team, and require a comprehensive understanding of the patient's anatomy and physiology, an appropriate therapeutic plan, a meticulously executed and technically optimal operation facilitated by lesion-specific anesthesia and perfusion strategies, and skilled perioperative care.",
   "The presence of important residual lesions after surgery is a principal factor contributing to adverse outcomes and may necessitate early unplanned cardiac reinterventions during the index hospitalization.",
   "Such reinterventions occur in approximately 5% of all pediatric cardiac operations, with a higher incidence in younger patients and in more complex procedures.",
   "The presence of significant residual lesions and the need for unplanned reinterventions are strongly associated with increased morbidity, increased mortality and greater resource use.",
   "There is wide center-level variation in the incidence and timing of unplanned reinterventions, which points to a concrete opportunity for quality improvement.",
   "The statement reviews postoperative monitoring strategies and the clinical indicators that should raise suspicion of a residual lesion, together with an overview of the noninvasive imaging modalities used to identify and quantify them.",
   "The roles of diagnostic and interventional cardiac catheterization in the management of residual lesions are discussed, along with surgical considerations for early reoperation.",
   "The importance of communication with patients and families is highlighted, and key areas for future investigation are identified."
  ],
  "conclusiones": "For clinical practice, the statement consolidates one operating principle: when the postoperative course after congenital cardiac surgery does not follow the expected trajectory, a residual lesion should be actively and early sought — first through postoperative monitoring and clinical indicators of suspicion, then through noninvasive imaging and, where appropriate, diagnostic or interventional catheterization or reoperation. Because this affects around 5% of operations, with higher risk in younger children and more complex surgery, and with wide variation between centers, each team should know its own reintervention rates and timing as a quality indicator. Explicit communication with the family about this possibility is part of the standard of care. The text does not provide numbered recommendations with a class or level of evidence."
 }
}

D["a40"] = {
 "title_en": "1-Year Outcomes of Drug-Coated Balloon Angioplasty Versus Drug-Eluting Stent for Coronary Artery Bypass Graft Lesions (J-PCI OUTCOME)",
 "title_es": "Resultados a 1 año de la angioplastia con balón liberador de fármaco frente al stent farmacoactivo en lesiones de injertos aortocoronarios (J-PCI OUTCOME)",
 "es": {
  "resumen": "Registro nacional japonés de 610 intervenciones sobre lesiones de injertos aortocoronarios, de las que 184 (30,2%) se realizaron solo con balón liberador de fármaco. Los MACE al año no difirieron entre la estrategia con stent farmacoactivo y la estrategia sin stent (10,3% frente a 8,6%; P = 0,69; HR ajustada 1,01; IC 95% 0,58-1,76).",
  "why": "el fallo de injerto es un problema frecuente y el material óptimo para tratarlo sigue discutiéndose, con poca evidencia comparativa directa. Este registro nacional muestra que la estrategia solo con balón liberador de fármaco ya representa casi un tercio de estos procedimientos en Japón y que, con los datos disponibles, no se asocia a peores resultados clínicos al año que el stent farmacoactivo contemporáneo. Es un dato observacional, sin aleatorización y con potencia limitada, así que sostiene el uso del balón liberador de fármaco como alternativa razonable en injertos —evitando dejar más metal en un vaso propenso a la degeneración— pero no demuestra superioridad ni equivalencia formal.",
  "deque": "El fallo del injerto tras la cirugía de revascularización coronaria es un problema clínico frecuente y se asocia a resultados cardiovasculares adversos. Aunque el intervencionismo coronario percutáneo (ICP) sobre lesiones de injertos se realiza con frecuencia, la estrategia de dispositivo óptima sigue debatiéndose, y el balón liberador de fármaco (DCB) ha emergido recientemente como alternativa sin stent. El objetivo del estudio fue comparar los resultados clínicos a 1 año entre la estrategia con stent farmacoactivo (DES) y la estrategia solo con DCB en pacientes sometidos a ICP de lesiones de injerto. Se analizaron los datos del J-PCI OUTCOME (Japanese Percutaneous Coronary Intervention Outcome Registry), un registro nacional de Japón, incluyendo a los pacientes tratados con DES o con ICP sin stent mediante DCB sobre lesiones de injerto entre 2017 y 2020. La variable principal fueron los eventos cardiovasculares adversos mayores (MACE), definidos como el compuesto de muerte por cualquier causa, síndrome coronario agudo e ictus en el año siguiente al ICP. Las variables secundarias incluyeron los componentes individuales del MACE, la hemorragia mayor y la revascularización repetida planificada.",
  "resultados": "De las 610 ICP realizadas sobre lesiones de injerto, 184 (30,2%) fueron ICP sin stent con DCB. Las tasas de MACE al año no difirieron significativamente entre la estrategia con DES y la estrategia solo con DCB (10,3% frente a 8,6%; P = 0,69). No se observaron diferencias estadísticamente significativas en las variables secundarias. Tras el ajuste multivariable, la estrategia solo con DCB no se asoció a una diferencia significativa en el riesgo de MACE tras el ICP frente a la estrategia basada en DES (HR ajustada 1,01; IC 95% 0,58-1,76; P = 0,96).",
  "conclusiones": "El ICP sin stent con balón liberador de fármaco se utilizó con frecuencia en los pacientes sometidos a ICP de lesiones de injerto aortocoronario en Japón y no se asoció a una diferencia significativa en los resultados clínicos a 1 año en comparación con las estrategias contemporáneas de ICP basadas en stent farmacoactivo."
 },
 "en": {
  "resumen": "Japanese nationwide registry of 610 procedures on coronary bypass graft lesions, 184 of them (30.2%) performed with a drug-coated balloon only. One-year MACE did not differ between the drug-eluting stent and the stentless strategies (10.3% vs 8.6%; P = 0.69; adjusted HR 1.01; 95% CI 0.58-1.76).",
  "why": "graft failure is common and the optimal device to treat it remains debated, with little head-to-head evidence. This nationwide registry shows that a DCB-only strategy already accounts for almost a third of these procedures in Japan and that, with the available data, it is not associated with worse 1-year clinical outcomes than contemporary drug-eluting stents. These are observational, non-randomized data with limited power, so they support DCB as a reasonable alternative in grafts — avoiding leaving more metal in a vessel prone to degeneration — but demonstrate neither superiority nor formal equivalence.",
  "deque": "Graft failure after coronary artery bypass grafting is a common clinical problem associated with adverse cardiovascular outcomes. Although percutaneous coronary intervention (PCI) for bypass graft lesions is frequently performed, the optimal device strategy remains debated, and drug-coated balloons (DCB) have recently emerged as a stentless alternative. The study aimed to compare 1-year clinical outcomes between drug-eluting stent (DES) and DCB-only strategies in patients undergoing PCI for bypass graft lesions. Data were analysed from the J-PCI OUTCOME (Japanese Percutaneous Coronary Intervention Outcome Registry), a nationwide registry in Japan, including patients who underwent PCI with DES or stentless PCI with DCB for bypass graft lesions between 2017 and 2020. The primary endpoint was major adverse cardiovascular events (MACE), a composite of all-cause death, acute coronary syndrome and stroke within 1 year after PCI. Secondary endpoints included the individual components of MACE, major bleeding and planned repeat revascularization.",
  "resultados": "Of the 610 PCIs for bypass graft lesions, 184 (30.2%) were stentless PCIs with DCB. One-year MACE rates did not differ significantly between the DES and DCB-only strategies (10.3% vs 8.6%; P = 0.69). No statistically significant differences were observed in the secondary endpoints. After multivariable adjustment, the DCB-only strategy was not associated with a significant difference in MACE risk after PCI compared with the DES-based strategy (adjusted HR 1.01; 95% CI 0.58-1.76; P = 0.96).",
  "conclusiones": "Stentless PCI with DCB was frequently used in patients undergoing PCI for bypass graft lesions in Japan and was not associated with a significant difference in 1-year clinical outcomes compared with contemporary DES-based PCI strategies."
 }
}

D["a41"] = {
 "title_en": "Targeted left ventricular lead placement in biventricular pacing for heart failure: a national, multicentre, double-blind, randomised controlled trial in Denmark",
 "title_es": "Colocación dirigida del electrodo ventricular izquierdo en la estimulación biventricular para la insuficiencia cardiaca: ensayo nacional, multicéntrico, doble ciego y aleatorizado en Dinamarca",
 "es": {
  "resumen": "Ensayo danés nacional, doble ciego, con 1.000 pacientes con insuficiencia cardiaca y QRS ancho candidatos a estimulación biventricular. Dirigir el electrodo izquierdo al punto de activación eléctrica más tardía no redujo el compuesto de muerte u hospitalización no planificada por insuficiencia cardiaca frente a la colocación posterolateral convencional (28% frente a 26%; HR 1,10; IC 95% 0,86-1,39; p = 0,45).",
  "why": "los datos observacionales llevaban años sugiriendo que colocar el electrodo izquierdo en la zona de activación más tardía mejora la respuesta a la terapia de resincronización, y esa idea se había ido incorporando a la práctica de muchos implantadores. Este es el ensayo aleatorizado, doble ciego y de tamaño nacional que pone a prueba esa hipótesis, y el resultado es claramente neutro, además de con más complicaciones relacionadas con el electrodo en el grupo dirigido. Conviene notar que la diferencia real de retraso de activación conseguida entre grupos fue de solo 9 ms, un margen estrecho que ayuda a interpretar la neutralidad. En la práctica, el mensaje es que la colocación convencional en una rama posterolateral no apical sigue siendo un objetivo adecuado y que no está justificado alargar o complicar el procedimiento para perseguir el punto de activación más tardía.",
  "deque": "La posición del electrodo ventricular izquierdo es un determinante clave de una estimulación biventricular óptima en la insuficiencia cardiaca, y los datos observacionales indican mejores resultados en los pacientes con activación miocárdica tardía en el punto donde se sitúa el electrodo. Los autores se propusieron comprobar si dirigir el electrodo izquierdo al lugar de activación eléctrica más tardía mejora los resultados. En este ensayo nacional, aleatorizado, controlado, doble ciego y de superioridad se incluyeron pacientes de los cinco centros universitarios daneses que realizan implante de dispositivos, con insuficiencia cardiaca y QRS ancho bajo tratamiento médico según guías, candidatos a estimulación biventricular. Se asignaron aleatoriamente 1:1 al grupo de intervención, con colocación del electrodo izquierdo en el punto de activación eléctrica más tardía dentro de las ramas del seno coronario, o al grupo control, con colocación en una rama posterolateral no apical. La variable principal fue el compuesto de tiempo hasta la muerte o la primera hospitalización no planificada por insuficiencia cardiaca. Se empleó aleatorización por bloques y se enmascaró a los pacientes y a todo el personal del estudio salvo al personal de quirófano. El análisis siguió un enfoque por intención de tratar modificada y la seguridad se evaluó en todos los pacientes correctamente asignados. El ensayo está registrado en ClinicalTrials.gov (NCT03280862) y está completo.",
  "resultados": "Entre el 20 de marzo de 2018 y el 3 de junio de 2024 se incluyeron 1.001 pacientes (255 mujeres y 746 varones); 499 se asignaron al grupo de intervención y 502 al grupo control. Se excluyó a un paciente incorrectamente incluido, quedando 1.000 pacientes para el análisis por intención de tratar modificada. La activación eléctrica en el electrodo ventricular izquierdo fue de media 9 milisegundos (IC 95% 5-13) más tardía en el grupo de intervención. El seguimiento se completó el 27 de febrero de 2026, tras una mediana de 45,8 meses (RIC 28,5-65,7). La variable principal ocurrió en 139 (28%) de 499 pacientes del grupo de intervención y en 128 (26%) de 501 del grupo control (hazard ratio 1,10; IC 95% 0,86-1,39; p = 0,45). El riesgo global de complicaciones fue similar entre grupos (71 pacientes [14%] en el grupo de intervención frente a 64 [13%] en el control), pero las complicaciones relacionadas con el electrodo fueron más frecuentes en el grupo de intervención. Se produjo una muerte relacionada con el procedimiento en el grupo de intervención.",
  "conclusiones": "En pacientes con insuficiencia cardiaca y QRS prolongado, la colocación dirigida del electrodo ventricular izquierdo en el punto de activación eléctrica más tardía no redujo el compuesto de muerte u hospitalización no planificada por insuficiencia cardiaca en comparación con la colocación convencional en una rama posterolateral no apical."
 },
 "en": {
  "resumen": "Danish nationwide, double-blind trial in 1,000 patients with heart failure and wide QRS eligible for biventricular pacing. Targeting the left ventricular lead at the site of latest electrical activation did not reduce the composite of death or unplanned heart failure hospitalisation compared with conventional posterolateral placement (28% vs 26%; HR 1.10; 95% CI 0.86-1.39; p = 0.45).",
  "why": "observational data had for years suggested that placing the left ventricular lead at the site of latest activation improves response to cardiac resynchronization, and the idea had made its way into many implanters' practice. This is the nationwide, randomised, double-blind trial that tests that hypothesis, and the result is clearly neutral, with more lead-related complications in the targeted group. It is worth noting that the actual difference in activation delay achieved between groups was only 9 ms, a narrow margin that helps interpret the neutral result. In practice, the message is that conventional placement in a posterolateral non-apical branch remains an adequate target and that lengthening or complicating the procedure to chase the latest-activation site is not justified.",
  "deque": "Left ventricular lead position is a key determinant of optimal biventricular pacing in heart failure, and observational data indicate better outcomes in patients with late myocardial activation at the lead site. The authors aimed to test whether targeting the left ventricular lead at the site of latest electrical activation improves outcomes. In this national, randomised, controlled, double-blinded, superiority trial, patients were enrolled from all five Danish university centres performing device implantation, with heart failure and wide QRS on guideline-directed medication and eligible for biventricular pacing. Patients were randomly assigned 1:1 to the intervention group, with left ventricular lead placement at the latest electrically activated site within the coronary sinus branches, or to the control group, with lead placement in a posterolateral non-apical branch. The primary outcome was a composite of time to death or first unplanned hospitalisation for heart failure. Block randomisation was used and patients and all study personnel (except operating room personnel) were masked to allocation. Analysis followed a modified intention-to-treat approach, and safety was assessed in all correctly assigned patients. The trial is registered at ClinicalTrials.gov (NCT03280862) and is complete.",
  "resultados": "From 20 March 2018 to 3 June 2024, 1,001 patients were included (255 females and 746 males); 499 were randomly assigned to the intervention group and 502 to the control group. One incorrectly enrolled patient was excluded, leaving 1,000 patients for the modified intention-to-treat analysis. Electrical activation at the left ventricular lead was a mean of 9 milliseconds (95% CI 5-13) later in the intervention group. Follow-up was completed on 27 February 2026, after a median of 45.8 months (IQR 28.5-65.7). The primary endpoint occurred in 139 (28%) of 499 patients in the intervention group and 128 (26%) of 501 in the control group (hazard ratio 1.10; 95% CI 0.86-1.39; p = 0.45). Overall complication risk was similar between groups (71 patients [14%] in the intervention group vs 64 [13%] in the control group), but lead-related complications were more frequent in the intervention group. One procedure-related death occurred in the intervention group.",
  "conclusiones": "In patients with heart failure and prolonged QRS, targeted left ventricular lead placement at the site of latest electrical activation did not reduce the composite endpoint of death or unplanned hospitalisation for heart failure compared with conventional lead placement in a posterolateral, non-apical position."
 }
}

D["a42"] = {
 "title_en": "Immediate Ambulatory Electrocardiographic Monitoring in Syncope (ASPIRED)",
 "title_es": "Monitorización electrocardiográfica ambulatoria inmediata en el síncope (ASPIRED)",
 "es": {
  "resumen": "Ensayo aleatorizado abierto en 45 hospitales del Reino Unido con 2.234 pacientes con síncope inexplicado tras la evaluación en urgencias. La monitorización electrocardiográfica ambulatoria de 14 días no redujo el número medio de episodios de síncope referidos por el paciente al año frente a la atención estándar (1,37 frente a 1,58; razón de tasas de incidencia 0,89; IC 95% 0,68-1,18; P = 0,42).",
  "why": "la monitorización prolongada precoz se ha extendido con la lógica intuitiva de que documentar antes una arritmia debería traducirse en tratarla antes y en menos recurrencias. Este ensayo, grande y realizado en el escenario real de urgencias, demuestra que esa cadena no se cumple: colocar un registrador de 14 días de forma inmediata no cambió la carga de síncopes al año. Además, los eventos adversos fueron más numerosos en el grupo monitorizado (49 frente a 8), en su mayoría no graves. Para el clínico, esto desaconseja la monitorización sistemática de 14 días como estrategia de rutina en todo síncope inexplicado de urgencias y devuelve el foco a la selección de pacientes por riesgo.",
  "deque": "En los pacientes con síncope que acuden a urgencias para evaluación, diagnosticar una arritmia cardiaca subyacente sigue siendo difícil. Se realizó un ensayo abierto, aleatorizado y controlado en 45 hospitales del Reino Unido para evaluar los efectos de la monitorización cardiaca de 14 días sobre el diagnóstico, el tratamiento y los resultados en pacientes con síncope. Los adultos con síncope que permanecía inexplicado tras la evaluación en urgencias se asignaron en proporción 1:1 a monitorización electrocardiográfica ambulatoria de 14 días (grupo de intervención) o a recibir la atención estándar proporcionada a los pacientes con síncope inexplicado en cada centro participante (grupo de atención estándar). La variable principal fue el número medio de episodios de síncope referidos por el paciente al año.",
  "resultados": "Se aleatorizaron 2.234 pacientes: 1.123 al grupo de intervención y 1.111 al grupo de atención estándar. La edad media fue de 58,3 años y el 52,1% eran varones. Tras excluir a los pacientes que no completaron ningún seguimiento, se incluyeron 1.970 pacientes en el análisis principal (1.004 en el grupo de intervención y 966 en el de atención estándar). El número medio (±DE) de episodios de síncope referidos por el paciente al año fue de 1,37 ± 5,10 en el grupo de intervención y de 1,58 ± 8,56 en el de atención estándar (razón de tasas de incidencia 0,89; IC 95% 0,68-1,18; P = 0,42). Se notificaron 49 eventos adversos en el grupo de intervención y 8 en el grupo de atención estándar, con 1 evento adverso grave en cada grupo.",
  "conclusiones": "Entre los pacientes con síncope que permanecía inexplicado tras la evaluación en urgencias, el uso de monitorización electrocardiográfica ambulatoria de 14 días no dio lugar a un número significativamente menor de episodios de síncope referidos por el paciente al año en comparación con la atención estándar. (Financiado por la British Heart Foundation y NHS Research Scotland; ASPIRED, registro ISRCTN número ISRCTN10278811)."
 },
 "en": {
  "resumen": "Open-label randomized trial across 45 UK hospitals in 2,234 patients with syncope that remained unexplained after emergency department evaluation. Fourteen-day ambulatory ECG monitoring did not reduce the mean number of patient-reported syncope episodes at 1 year versus standard care (1.37 vs 1.58; incidence rate ratio 0.89; 95% CI 0.68-1.18; P = 0.42).",
  "why": "early prolonged monitoring has spread on the intuitive logic that documenting an arrhythmia sooner should translate into treating it sooner and into fewer recurrences. This large trial, run in the real-world emergency setting, shows that the chain does not hold: fitting a 14-day recorder immediately did not change the syncope burden at 1 year. Adverse events were also more numerous in the monitored group (49 vs 8), mostly non-serious. For the clinician this argues against systematic 14-day monitoring as a routine strategy for every unexplained syncope in the emergency department and shifts the focus back to risk-based patient selection.",
  "deque": "In patients with syncope who present to the emergency department for evaluation, diagnosing an underlying cardiac arrhythmia remains difficult. An open-label, randomized, controlled trial was conducted at 45 hospitals in the United Kingdom to assess the effects of 14-day cardiac monitoring on diagnosis, treatment and outcomes in patients with syncope. Adults with syncope that remained unexplained after evaluation in the emergency department were assigned in a 1:1 ratio to undergo 14-day ambulatory electrocardiographic (ECG) monitoring (intervention group) or to receive the standard care provided for patients with unexplained syncope at each participating site (standard-care group). The primary outcome was the mean number of patient-reported episodes of syncope at 1 year.",
  "resultados": "A total of 2,234 patients underwent randomization: 1,123 were assigned to the intervention group and 1,111 to the standard-care group. Mean age was 58.3 years and 52.1% were male. After exclusion of patients who did not complete any follow-up, 1,970 patients were included in the primary analysis (1,004 in the intervention group and 966 in the standard-care group). The mean (±SD) number of patient-reported syncope episodes at 1 year was 1.37±5.10 in the intervention group and 1.58±8.56 in the standard-care group (incidence rate ratio 0.89; 95% CI 0.68 to 1.18; P = 0.42). A total of 49 adverse events were reported in the intervention group and 8 in the standard-care group, with 1 serious adverse event in each group.",
  "conclusiones": "Among patients with syncope that remained unexplained after evaluation in the emergency department, the use of 14-day ambulatory ECG monitoring did not result in significantly fewer patient-reported syncope episodes at 1 year than standard care. (Funded by the British Heart Foundation and National Health Service Research Scotland; ASPIRED ISRCTN Registry number, ISRCTN10278811.)"
 }
}

D["a43"] = {
 "title_en": "Cryoballoon ablation versus antiarrhythmic drug therapy as initial treatment for persistent atrial fibrillation: the multicenter randomized CEPAF trial",
 "title_es": "Ablación con criobalón frente a tratamiento antiarrítmico como tratamiento inicial de la fibrilación auricular persistente: el ensayo multicéntrico aleatorizado CEPAF",
 "es": {
  "resumen": "Ensayo multicéntrico aleatorizado en 320 pacientes con fibrilación auricular persistente sin tratamiento previo. La ablación con criobalón de primera línea redujo la recurrencia de taquiarritmia auricular entre los días 91 y 365 frente al antiarrítmico (18,8% frente a 44,4%; diferencia absoluta −25,6 puntos porcentuales; IC 95% −35,4 a −15,8; P < 0,001).",
  "why": "la ablación de primera línea estaba respaldada sobre todo en la fibrilación auricular paroxística, y la evidencia en la forma persistente de pacientes vírgenes de tratamiento era escasa. CEPAF cubre ese hueco con un diseño aleatorizado y muestra una reducción absoluta de recurrencias muy amplia, cercana a 26 puntos porcentuales, acompañada de una mejoría de la calidad de vida específica de la enfermedad casi tres veces mayor que con fármacos. También reduce la recurrencia precoz, en los primeros 90 días, un periodo que habitualmente se considera de blanking. Para la consulta, refuerza la conversación con el paciente con fibrilación auricular persistente sintomática de reciente diagnóstico sobre ofrecer la ablación antes de agotar la vía farmacológica.",
  "deque": "La evidencia que respalda la ablación con criobalón (CBA) de primera línea en la fibrilación auricular persistente (FAPers) sin tratamiento previo es limitada, de modo que los autores compararon la CBA con el tratamiento antiarrítmico (AAD) dirigido por guías en esta forma avanzada de la enfermedad. En este ensayo multicéntrico, prospectivo, aleatorizado y abierto se asignaron 320 pacientes sintomáticos con FAPers y sin tratamiento previo, en proporción 1:1, a CBA o a tratamiento antiarrítmico. La variable principal fue la primera recurrencia documentada de taquiarritmia auricular de al menos 30 segundos de duración durante los días 91 a 365. Las variables secundarias incluyeron la recurrencia durante los días 1-90 y 1-365, el tiempo hasta la primera recurrencia, la calidad de vida y la seguridad.",
  "resultados": "En la población por intención de tratar, la recurrencia durante los días 91-365 ocurrió en 30/160 (18,8%) pacientes asignados a CBA y en 71/160 (44,4%) asignados a tratamiento antiarrítmico (diferencia absoluta −25,6 puntos porcentuales; IC 95% −35,4 a −15,8; P < 0,001). El análisis de soporte de tiempo hasta el evento favoreció a la CBA (hazard ratio para AAD frente a CBA 2,29; IC 95% 1,48-3,56; log-rank P < 0,001). En la comparación CBA frente a AAD, la recurrencia global durante los días 1-365 fue del 23,8% frente al 55,6%, y la recurrencia precoz del 11,2% frente al 28,1% (ambas P < 0,001). La mejoría de la puntuación AFEQT fue mayor con CBA (17,3 frente a 6,6 puntos; P < 0,001), mientras que las puntuaciones de los componentes del SF-12 no difirieron significativamente. Los eventos adversos registrados en los formularios de eventos fueron infrecuentes en ambas cohortes.",
  "conclusiones": "En pacientes seleccionados con fibrilación auricular persistente sin tratamiento previo, la ablación con criobalón de primera línea redujo la recurrencia de taquiarritmia auricular y mejoró la calidad de vida específica de la enfermedad en comparación con el tratamiento antiarrítmico."
 },
 "en": {
  "resumen": "Multicenter randomized trial in 320 treatment-naive patients with persistent atrial fibrillation. First-line cryoballoon ablation reduced atrial tachyarrhythmia recurrence between days 91 and 365 compared with antiarrhythmic drugs (18.8% vs 44.4%; absolute difference −25.6 percentage points; 95% CI −35.4 to −15.8; P < 0.001).",
  "why": "first-line ablation was supported mainly in paroxysmal atrial fibrillation, and evidence in treatment-naive persistent disease was scarce. CEPAF fills that gap with a randomized design and shows a very large absolute reduction in recurrence, close to 26 percentage points, together with an almost threefold greater improvement in disease-specific quality of life than with drugs. It also reduces early recurrence within the first 90 days, a period usually regarded as blanking. In the clinic it strengthens the conversation with newly diagnosed, symptomatic persistent atrial fibrillation patients about offering ablation before exhausting the pharmacological route.",
  "deque": "Evidence supporting first-line cryoballoon ablation (CBA) in treatment-naive persistent atrial fibrillation (PersAF) is limited, so the authors compared CBA with guideline-directed antiarrhythmic drug (AAD) therapy in this advanced form of the disease. This multicenter, prospective, randomized, open-label trial assigned 320 symptomatic, treatment-naive patients with PersAF 1:1 to CBA or AAD therapy. The primary endpoint was the first documented atrial tachyarrhythmia recurrence lasting at least 30 seconds during days 91-365. Secondary endpoints included recurrence during days 1-90 and 1-365, time to first recurrence, quality of life and safety.",
  "resultados": "In the intention-to-treat population, recurrence during days 91-365 occurred in 30/160 (18.8%) patients assigned to CBA and 71/160 (44.4%) assigned to AAD therapy (absolute difference −25.6 percentage points; 95% CI −35.4 to −15.8; P < 0.001). The supportive time-to-event analysis favoured CBA (hazard ratio for AAD vs CBA 2.29; 95% CI 1.48-3.56; log-rank P < 0.001). In CBA vs AAD comparisons, overall recurrence during days 1-365 was 23.8% vs 55.6%, and early recurrence was 11.2% vs 28.1% (both P < 0.001). Improvement in AFEQT score was greater with CBA (17.3 vs 6.6 points; P < 0.001), whereas SF-12 component scores did not differ significantly. Adverse events recorded on event forms were infrequent in both cohorts.",
  "conclusiones": "In selected treatment-naive patients with persistent atrial fibrillation, first-line cryoballoon ablation reduced atrial tachyarrhythmia recurrence and improved disease-specific quality of life compared with antiarrhythmic drug therapy."
 }
}

D["a44"] = {
 "title_en": "Pacemaker-implantation and atrioventricular-node ablation vs pulmonary vein isolation for elderly patients with persistent atrial fibrillation: the ABLATE versus PACE trial",
 "title_es": "Implante de marcapasos y ablación del nodo auriculoventricular frente a aislamiento de venas pulmonares en pacientes ancianos con fibrilación auricular persistente: el ensayo ABLATE versus PACE",
 "es": {
  "resumen": "Ensayo aleatorizado abierto en 196 pacientes de 75 años o más (mediana 82) con fibrilación auricular persistente sintomática y fracción de eyección normal. A los 12 meses, la estrategia de marcapasos más ablación del nodo AV redujo la variable principal frente al aislamiento de venas pulmonares (24% frente a 46%; HR 0,45; IC 95% 0,27-0,74; P = 0,002).",
  "why": "en el paciente muy anciano con fibrilación auricular persistente el aislamiento de venas pulmonares se usa ampliamente pese a una tasa de éxito limitada, y hasta ahora faltaba una comparación aleatorizada directa con la estrategia de ablate-and-pace. Este ensayo, con una mediana de edad de 82 años, muestra que la estrategia de control de frecuencia definitiva reduce a menos de la mitad los eventos del compuesto, a expensas sobre todo de evitar hospitalizaciones por fibrilación auricular y cardioversiones. El matiz relevante para la práctica es que el desglose de eventos va en direcciones opuestas: menos ingresos por arritmia con marcapasos y ablación del nodo, pero más ingresos por insuficiencia cardiaca (23 frente a 11). La mortalidad, las complicaciones cardiovasculares y la calidad de vida no difirieron.",
  "deque": "El envejecimiento poblacional está aumentando la prevalencia de la fibrilación auricular (FA). En los pacientes ancianos con FA persistente, el aislamiento de venas pulmonares (PVI) tiene un éxito limitado pero se emplea de forma generalizada, mientras que el implante de marcapasos con ablación del nodo auriculoventricular (PM+AVNA) proporciona un control sintomático eficaz; los efectos relativos de PM+AVNA frente a PVI sobre las hospitalizaciones y otros resultados en el anciano seguían siendo desconocidos. Este ensayo multicéntrico, abierto e iniciado por investigadores aleatorizó a pacientes de 75 años o más con FA persistente sintomática y fracción de eyección del ventrículo izquierdo normal a la estrategia de PM+AVNA o a la de PVI. La variable principal fue un compuesto de hospitalización por arritmia auricular o insuficiencia cardiaca, cardioversión eléctrica ambulatoria o actualización a terapia de resincronización cardiaca por disfunción ventricular izquierda. Las variables secundarias incluyeron la muerte por cualquier causa, el ictus, las complicaciones relacionadas con el tratamiento y la calidad de vida.",
  "resultados": "Doce centros de Alemania y Austria aleatorizaron a 196 pacientes (mediana de edad 82 años). A los 12 meses, un primer evento de la variable principal ocurrió en 24 de 98 pacientes (24%) asignados a PM+AVNA y en 45 de 98 (46%) asignados a PVI (hazard ratio 0,45; IC 95% 0,27-0,74; P = 0,002). Se produjeron en total 29 y 84 eventos de la variable principal, respectivamente, consistentes principalmente en hospitalizaciones por FA y cardioversiones en el grupo de PVI (54 y 19, respectivamente, frente a 3 y 1 en el grupo de PM+AVNA) y en hospitalizaciones por insuficiencia cardiaca en el grupo de PM+AVNA (23, frente a 11 en el grupo de PVI). La incidencia de complicaciones cardiovasculares y la mortalidad, así como la calidad de vida, no difirieron de forma estadísticamente significativa.",
  "conclusiones": "En pacientes ancianos con fibrilación auricular persistente, el implante de marcapasos con ablación del nodo auriculoventricular se asoció a menos eventos de la variable principal que el aislamiento de venas pulmonares a lo largo de 12 meses de seguimiento."
 },
 "en": {
  "resumen": "Open-label randomized trial in 196 patients aged 75 years or older (median 82) with symptomatic persistent atrial fibrillation and normal ejection fraction. At 12 months, pacemaker implantation plus AV-node ablation reduced the primary endpoint compared with pulmonary vein isolation (24% vs 46%; HR 0.45; 95% CI 0.27-0.74; P = 0.002).",
  "why": "in very elderly patients with persistent atrial fibrillation, pulmonary vein isolation is widely used despite limited success rates, and a direct randomized comparison with the ablate-and-pace strategy was lacking. This trial, with a median age of 82 years, shows that a definitive rate-control strategy more than halves composite events, mainly by avoiding atrial fibrillation hospitalisations and cardioversions. The practically relevant nuance is that the event breakdown runs in opposite directions: fewer arrhythmia admissions with pacemaker plus node ablation, but more heart failure admissions (23 vs 11). Mortality, cardiovascular complications and quality of life did not differ.",
  "deque": "Population aging is increasing the prevalence of atrial fibrillation (AF). In elderly patients with persistent AF, pulmonary vein isolation (PVI) has limited success but is widely used, whereas pacemaker implantation with atrioventricular-node ablation (PM+AVNA) provides effective symptom control; the relative effects of PM+AVNA versus PVI on hospitalisations and other outcomes in the elderly remained unknown. This investigator-initiated, multicentre, open-label trial randomised patients aged ≥75 years with symptomatic persistent AF and normal left ventricular ejection fraction to PM+AVNA or PVI treatment strategies. The primary endpoint was a composite of hospitalisation for atrial arrhythmia or heart failure, outpatient electrical cardioversion, or upgrade to cardiac resynchronisation therapy for left ventricular dysfunction. Secondary endpoints included all-cause death, stroke, treatment-related complications and quality of life.",
  "resultados": "Twelve centres in Germany and Austria randomised 196 patients (median age 82 years). At 12 months, a first primary endpoint event occurred in 24 of 98 patients (24%) assigned to PM+AVNA and 45 of 98 patients (46%) assigned to PVI (hazard ratio 0.45; 95% CI 0.27-0.74; P = 0.002). A total of 29 and 84 primary endpoint events occurred respectively, consisting principally of AF hospitalisations and cardioversions in the PVI group (54 and 19 respectively, vs 3 and 1 in the PM+AVNA group) and of heart failure hospitalisations in the PM+AVNA group (23, vs 11 in the PVI group). The incidence of cardiovascular complications and mortality, as well as quality of life, were not statistically different.",
  "conclusiones": "In elderly patients with persistent atrial fibrillation, PM+AVNA was associated with fewer primary endpoint events than PVI over a 12-month follow-up period."
 }
}

D["a45"] = {
 "title_en": "Edoxaban Antithrombotic Therapy in Diabetic Patients with Atrial Fibrillation and Stable Coronary Artery Disease: The EPIC-CAD Trial",
 "title_es": "Tratamiento antitrombótico con edoxabán en pacientes diabéticos con fibrilación auricular y enfermedad coronaria estable: el ensayo EPIC-CAD",
 "es": {
  "resumen": "Análisis según el estado diabético del ensayo EPIC-CAD, con 1.040 pacientes con fibrilación auricular y enfermedad coronaria estable, de los que 421 (40,5%) eran diabéticos. La monoterapia con edoxabán redujo la variable principal a los 12 meses tanto en diabéticos (6,3% frente a 13,7%; HR 0,44) como en no diabéticos (6,7% frente a 16,3%; HR 0,39), sin interacción significativa (P = 0,78).",
  "why": "en el paciente con fibrilación auricular y coronariopatía estable existe una tentación clínica persistente de mantener un antiagregante añadido al anticoagulante cuando además hay diabetes, por el mayor riesgo aterotrombótico atribuido a esta población. Este análisis desmonta ese razonamiento: los diabéticos no tuvieron más eventos que los no diabéticos y el beneficio neto de retirar el antiagregante fue igual de consistente en ambos grupos, con una reducción de riesgo superior al 50%. Refuerza la recomendación de monoterapia anticoagulante a largo plazo sin excepciones por diabetes.",
  "deque": "El régimen antitrombótico apropiado para los pacientes diabéticos con fibrilación auricular (FA) y enfermedad coronaria (EC) estable que presentan un alto riesgo aterotrombótico sigue siendo incierto, y los autores evaluaron si los efectos de las distintas estrategias antitrombóticas difieren según el estado diabético. EPIC-CAD (Edoxaban versus Edoxaban with Antiplatelet Agent in Patients with Atrial Fibrillation and Chronic Stable Coronary Artery Disease) fue un ensayo aleatorizado que comparó la monoterapia con edoxabán frente al tratamiento antitrombótico dual (edoxabán más un único antiagregante) en pacientes con FA y EC estable. La variable principal fue un compuesto de muerte por cualquier causa, infarto de miocardio, ictus, embolia sistémica, revascularización urgente no planificada y hemorragia mayor o clínicamente relevante no mayor a los 12 meses.",
  "resultados": "De los 1.040 pacientes aleatorizados, 421 (40,5%) tenían diabetes. No hubo diferencias en la incidencia de la variable principal entre pacientes diabéticos y no diabéticos (9,7% frente a 11,6%; hazard ratio [HR] 0,82; IC 95% 0,56-1,20; P = 0,30). La incidencia de la variable principal a los 12 meses fue significativamente menor con monoterapia de edoxabán que con tratamiento antitrombótico dual tanto en los pacientes diabéticos (6,3% frente a 13,7%; HR 0,44; IC 95% 0,23-0,83; P = 0,01) como en los no diabéticos (6,7% frente a 16,3%; HR 0,39; IC 95% 0,23-0,65; P = 0,001), sin interacción significativa entre el estado diabético y la estrategia de tratamiento asignada (P de interacción = 0,78).",
  "conclusiones": "El riesgo de la variable principal fue similar entre los pacientes diabéticos y no diabéticos con fibrilación auricular y enfermedad coronaria. Con independencia del estado diabético, la monoterapia con edoxabán condujo a un menor riesgo de la variable principal a los 12 meses que el tratamiento antitrombótico dual."
 },
 "en": {
  "resumen": "Analysis by diabetes status of the EPIC-CAD trial, with 1,040 patients with atrial fibrillation and stable coronary artery disease, 421 of them (40.5%) diabetic. Edoxaban monotherapy reduced the primary outcome at 12 months in both diabetic (6.3% vs 13.7%; HR 0.44) and non-diabetic patients (6.7% vs 16.3%; HR 0.39), with no significant interaction (P = 0.78).",
  "why": "in patients with atrial fibrillation and stable coronary disease there is a persistent clinical temptation to keep an antiplatelet agent on top of the anticoagulant when diabetes is also present, on the grounds of the higher atherothrombotic risk attributed to this population. This analysis dismantles that reasoning: diabetic patients did not have more events than non-diabetic ones, and the net benefit of dropping the antiplatelet agent was equally consistent in both groups, with a risk reduction of more than 50%. It reinforces the recommendation of long-term anticoagulant monotherapy with no exception for diabetes.",
  "deque": "The appropriate antithrombotic regimen for diabetic patients with atrial fibrillation (AF) and stable coronary artery disease (CAD) who are at high atherothrombotic risk remains uncertain, and the authors evaluated whether the effects of different antithrombotic strategies differ according to diabetes status. EPIC-CAD (Edoxaban versus Edoxaban with Antiplatelet Agent in Patients with Atrial Fibrillation and Chronic Stable Coronary Artery Disease) was a randomized trial comparing edoxaban monotherapy with dual antithrombotic therapy (edoxaban plus a single antiplatelet agent) in patients with AF and stable CAD. The primary outcome was a composite of death from any cause, myocardial infarction, stroke, systemic embolism, unplanned urgent revascularization, and major or clinically relevant non-major bleeding at 12 months.",
  "resultados": "Among the 1,040 randomized patients, 421 (40.5%) had diabetes. There were no differences in the incidence of the primary outcome between diabetic and non-diabetic patients (9.7% vs 11.6%; hazard ratio [HR] 0.82; 95% CI 0.56-1.20; P = 0.30). The incidence of the primary outcome at 12 months was significantly lower with edoxaban monotherapy than with dual antithrombotic therapy in both diabetic (6.3% vs 13.7%; HR 0.44; 95% CI 0.23-0.83; P = 0.01) and non-diabetic patients (6.7% vs 16.3%; HR 0.39; 95% CI 0.23-0.65; P = 0.001), with no significant interaction between diabetes status and the randomized treatment strategy (interaction P = 0.78).",
  "conclusiones": "The risk of the primary outcome was similar between diabetic and non-diabetic patients with atrial fibrillation and coronary artery disease. Irrespective of diabetes status, edoxaban monotherapy led to a lower risk of the primary outcome at 12 months than dual antithrombotic therapy."
 }
}

with open("/home/user/briefing-cardiovascular/generador/n13_data4.json", "w", encoding="utf-8") as f:
    json.dump(D, f, ensure_ascii=False, indent=1)

print("escrito", len(D))
